services:
  - type: web
    name: url-shortener-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
